<?php

declare(strict_types=1);

namespace CuyZ\ValinorBundle\Console;

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\Mapper\Tree\Message\NodeMessage;
use Symfony\Component\Console\Style\SymfonyStyle;

use function array_map;
use function array_slice;

/** @internal */
final class MappingErrorOutput
{
    public function __construct(
        private SymfonyStyle $io,
        private int $maxEntries,
    ) {}

    public function print(MappingError $error): void
    {
        $messages = $error->messages()->toArray();
        $count = count($messages);

        $this->io->section('Mapping errors');
        $this->io->writeln("A total of $count errors were found while trying to map to `{$error->type()}`");

        $cells = array_map(
            fn (NodeMessage $message) => [$message->path(), $message->toString()],
            array_slice($messages, 0, $this->maxEntries)
        );

        $this->io->table(['path', 'message'], $cells);

        if ($count > $this->maxEntries) {
            $remaining = $count - $this->maxEntries;

            $this->io->writeln("and $remaining more…");
        }

        $this->io->info(
            'The above message was generated by the Valinor Bundle, it can be disabled in the configuration of the bundle.'
        );
    }
}
